services:

  ca:
    build:
      context: .
      dockerfile: Dockerfile
      target: ca
    image: sandia-ca
    depends_on:
      - mongo
    ports:
    - "${CA_PORT}:8000"
  
  ocsp:
    build:
      context: .
      dockerfile: Dockerfile
      target: ocsp
    image: sandia-ocsp
    depends_on:
      - mongo
      - ca
    ports:
    - "${OCSP_PORT}:8001"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example